### ISSUE TITLE
CORS issue

### ISSUE THREAD

**Issue by erperejildo** [twilio/twilio-flex-token-validator#14]
I'm getting this error:
```
Access to fetch at 'https://my_url/transfer-chat' from origin 'https://flex.twilio.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

My function is pretty simple:
```
const JWEValidator = require('twilio-flex-token-validator').functionValidator;

exports.handler = JWEValidator(async function(context, event, callback) {

  const response = new Twilio.Response();

  // Set the status code to 200 OK
  response.setStatusCode(200);

  // Set the Content-Type Header
  response.appendHeader("Access-Control-Allow-Origin", "*");
  response.appendHeader(
    "Access-Control-Allow-Methods",
    "GET,PUT,POST,DELETE,OPTIONS"
  );
  response.appendHeader("Content-Type", "application/json");
  response.appendHeader(
    "Access-Control-Allow-Headers",
    "Content-Type, Authorization, Content-Length, X-Requested-With"
  );

  callback(null, response);
});
```

If I disable `Check for valid Twilio signature` it works fine.

`ACCOUNT_SID and AUTH_TOKEN` are enabled.

**Comment by ktalebian** [comment]
As you noticed, you _should_ disable `Check for valid Twilio signature`; with that enabled, Twilio Functions wouldn't even invoke your Function (hence the `CORS` error) if the request is not generated from Twilio.

This Token validator is a way to secure your Function outside of what `Check for valid Twilio signature` does.

I'll update the docs to mention that you should not have that checkbox enabled.

**Comment by qborreda** [comment]
Sorry to re-open this one, but I'm having a similar issue, and made sure the checkbox was not enabled. 

The experimental function just returns all the `context` and looks like 
```
const TokenValidator = require('twilio-flex-token-validator').functionValidator;

exports.handler = TokenValidator(function(context, event, callback) {
    const response = new Twilio.Response();
    response.appendHeader('Content-Type', 'application/json');
    response.appendHeader('Access-Control-Allow-Origin', '*');
    response.appendHeader('Access-Control-Allow-Methods', 'POST,OPTIONS');
    response.appendHeader('Access-Control-Allow-Headers', 'Content-Type');
    response.setStatusCode(200);
    response.setBody(JSON.stringify(context));
    callback(null, response);
});
```
Any clues why would this not let me access the function from a flex-plugin running on localhost?

**Comment by rapito** [comment]
@ktalebian Same as @qborreda I'm having the same issue, except that in my case I'm not testing locally and I don't see the that checkbox anywhere. Where is it supposed to be located? so I can try testing with that disabled.

**Comment by leognmotta** [comment]
same issue as above

**Comment by ruairidhwm** [comment]
Same issue here.

**Comment by JackCrish** [comment]
same issue

**Comment by Krishna-najpk** [comment]
Same issue. Is it solved?
