### ISSUE TITLE
Token was not provided

### ISSUE THREAD

**Issue by erperejildo** [twilio/twilio-flex-token-validator#16]
### Description

I get this error: 
```
Unauthorized: Token was not provided XRAY TraceId: 1-5d6f96ac-8c2...
```

### Versions

| package                       | version |
| ------------------------------| ------- |
| `twilio-flex-token-validator` | `1.5.0` |
| `node`                        | `Twilio hosted` |
| `npm`                         | `Twilio hosted` |

### Steps to Reproduce

Please provide the steps to reproduce this bug:

1. Run the function with the token

### Expected Behavior

I shouldn't get any error and my function should work the same as it was working before

### Additional Context

This is working for some other clients. What I did here:
- Enabled ACCOUNT_SID and AUTH_TOKEN [here](https://www.twilio.com/console/functions/configure)
- Installed `twilio-flex-token-validator` dependency with version `*` [here](https://www.twilio.com/console/functions/configure)
- Update my function from:
```
exports.handler = function(context, event, callback) {
```
to:
```
const TokenValidator = require("twilio-flex-token-validator").functionValidator;

exports.handler = TokenValidator(async function(context, event, callback) {
```

**Comment by ktalebian** [comment]
@erperejildo are you POSTing the token as `Token` parameter (or passing it as `?Token=` query parameter)? 

Please see https://github.com/twilio/twilio-flex-token-validator#using-in-twilio-function, specifically `This validator assumes that the token is provided as the Token key. The successful result of the token validation is added to event.TokenResult.`

**Comment by erperejildo** [comment]
Not sure to understand. I have my function exactly like this:
```
const TokenValidator = require('twilio-flex-token-validator').functionValidator;

exports.handler = TokenValidator(function(context, event, callback) {
    // Your normal Twilio Function goes here.
    // This block will only be called if your token is validated, otherwise it returns a 403.
});
```

I'm not POSTing any token directly

**Comment by ktalebian** [comment]
That's the problem; you should be including the JWE token when you are calling your Twilio Function. Please refer to [this guide](https://www.twilio.com/docs/flex/call-functions-from-plugins).

I'll update the doc to reference this guide.

**Comment by erperejildo** [comment]
Fair enough. I'll close this ticket then.
Any question I'll post it here

**Comment by erperejildo** [comment]
@ktalebian, what's the difference from `manager.store.getState().flex.session.ssoTokenPayload.token` and `manager.user.token`? Both return the same

**Comment by ktalebian** [comment]
The two are identical, and so `manager.user.token` should be used as it is shorter.
